layout_spectrum: 0.1235983416768215
typography_spectrum: 0.46735506485677375
color:
  brandStrength: 0.874804755182992
  lightness: 0.7526150103151282
  saturation: 0.17583647825238805
  rhythmicContrast: 0.3297724150700292
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
github: true
author:
  name: Peter Jansen
  email: p.jansen@mac.com
logo: null
name: Walking with the Coach
title: Walking with the Coach
content: []
description: Tools for a happy life
purpose:
  - type: external
    url: 'https://youtu.be/Zu4l1pHV7KA'
    label: Subscribe to our YouTube Channel
